added default for rsync_port
git-svn-id: https://svn.apache.org/repos/asf/incubator/solr/trunk@388620 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/scripts/snappuller b/src/scripts/snappuller
--- a/src/scripts/snappuller
+++ b/src/scripts/snappuller
@@ -93,11 +93,18 @@ then
     exit 1
 fi
 
+# try to determine rsyncd port number from $confFile if not specified on
+# command line, default to solr_port+10000
 if [[ -z ${rsyncd_port} ]]
 then
-    echo "rsyncd port number of master server missing in $confFile or command line."
-    echo "$USAGE"
-    exit 1
+    if [[ "${solr_port}" ]]
+    then
+        rsyncd_port=`expr 10000 + ${solr_port}`
+    else
+        echo "rsyncd port number of master server missing in $confFile or command line."
+        echo "$USAGE"
+        exit 1
+    fi
 fi
 
 if [[ -z ${master_data_dir} ]]
