SOLR-7024: bin/solr: Improve java detection and error messages (merge trunk r1654434)
git-svn-id: https://svn.apache.org/repos/asf/lucene/dev/branches/lucene_solr_5_0@1654438 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/solr/bin/solr b/solr/bin/solr
--- a/solr/bin/solr
+++ b/solr/bin/solr
@@ -119,12 +119,27 @@ elif [ -n "$JAVA_HOME" ]; then
       break
     fi
   done
+  if [ -z "$JAVA" ]; then
+    echo >&2 "The currently defined JAVA_HOME ($JAVA_HOME) refers"
+    echo >&2 "to a location where Java could not be found.  Aborting."
+    echo >&2 "Either fix the JAVA_HOME variable or remove it from the"
+    echo >&2 "environment so that the system PATH will be searched."
+    exit 1
+  fi
 else
   JAVA=java
 fi
 
 # test that Java exists and is executable on this server
-$JAVA -version >/dev/null 2>&1 || { echo >&2 "Java is required to run Solr! Please install Java 7 or 8 before running this script."; exit 1; }
+$JAVA -version >/dev/null 2>&1 || {
+  echo >&2 "Java not found, or an error was encountered when running java."
+  echo >&2 "A working Java 8 is required to run Solr!"
+  echo >&2 "Please install Java 8 or fix JAVA_HOME before running this script."
+  echo >&2 "Command that we tried: '${JAVA} -version'"
+  echo >&2 "Active Path:"
+  echo >&2 "${PATH}"
+  exit 1
+}
 
 # URL scheme for contacting Solr
 SOLR_URL_SCHEME=http
